; Form Designer for Purebasic - 5.31
; Warning: this file uses a strict syntax, if you edit it, make sure to respect the Form Designer limitation or it won't be opened again.

;
; This code is automatically generated by the FormDesigner.
; Manual modification is possible to adjust existing commands, but anything else will be dropped when the code is compiled.
; Event procedures needs to be put in another source file.
;

Global Window_0

Global Button_0, Button_0_Copy1, Button_0_Copy2, Button_0_Copy3, Button_0_Copy4, Text_0


Procedure OpenWindow_0(x = 0, y = 0, width = 200, height = 180)
  Window_0 = OpenWindow(#PB_Any, x, y, width, height, "wsutils", #PB_Window_SystemMenu)
  Button_0 = ButtonGadget(#PB_Any, 20, 10, 70, 25, "СТРИП")
  Button_0_Copy1 = ButtonGadget(#PB_Any, 110, 10, 70, 25, "ДЕЯТЬ")
  Button_0_Copy2 = ButtonGadget(#PB_Any, 20, 50, 70, 25, "ПЕРЕН")
  Button_0_Copy3 = ButtonGadget(#PB_Any, 110, 50, 70, 25, "ПЕРЕН2")
  Button_0_Copy4 = ButtonGadget(#PB_Any, 50, 90, 100, 25, "ДЕРАЗРЯД")
  Text_0 = TextGadget(#PB_Any, 20, 130, 160, 40, "")
EndProcedure

Procedure Window_0_Events(event)
  Select event
    Case #PB_Event_CloseWindow
      ProcedureReturn #False

    Case #PB_Event_Menu
      Select EventMenu()
      EndSelect

    Case #PB_Event_Gadget
      Select EventGadget()
      EndSelect
  EndSelect
  ProcedureReturn #True
EndProcedure

